# Basic
title: Hliang
subtitle: 个人站
description: 我说晚了你就不学了吗？
# 头像里面的标题
avatarTitle: HLiang
# 头像里面的描述
avatarDesc: 前端开发
url: "http://feibuli.github.io"

# Comment
comment:
    # disqus: 415533780
    duoshuo: 415533780 

# Social
social:
    weibo: 5975327672 
    github: feibuli
    # twitter: 
    mail: 415533780@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3   
#     host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/" 
    
